// <auto-generated />
using System;
using Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.3")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Domain.Entities.HomeBase", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("HomeBases");
                });

            modelBuilder.Entity("Domain.Entities.HomeBase", b =>
                {
                    b.OwnsOne("Domain.ValueObjects.Capacity", "Capacity", b1 =>
                        {
                            b1.Property<string>("HomeBaseId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<int>("Value")
                                .HasColumnType("int");

                            b1.HasKey("HomeBaseId");

                            b1.ToTable("HomeBases");

                            b1.WithOwner()
                                .HasForeignKey("HomeBaseId");
                        });

                    b.OwnsOne("Domain.ValueObjects.CoordinateLat", "CoordinateLat", b1 =>
                        {
                            b1.Property<string>("HomeBaseId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Value")
                                .HasColumnType("float");

                            b1.HasKey("HomeBaseId");

                            b1.ToTable("HomeBases");

                            b1.WithOwner()
                                .HasForeignKey("HomeBaseId");
                        });

                    b.OwnsOne("Domain.ValueObjects.CoordinateLon", "CoordinateLon", b1 =>
                        {
                            b1.Property<string>("HomeBaseId")
                                .HasColumnType("nvarchar(450)");

                            b1.Property<double>("Value")
                                .HasColumnType("float");

                            b1.HasKey("HomeBaseId");

                            b1.ToTable("HomeBases");

                            b1.WithOwner()
                                .HasForeignKey("HomeBaseId");
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("CoordinateLat")
                        .IsRequired();

                    b.Navigation("CoordinateLon")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
